### 회원 장바구니 조회
GET http://localhost:8083/api/cart
X-USER-ID: user123

### 회원 장바구니 조회 (w/o X-USER-ID 헤더)
GET http://localhost:8083/api/cart

### 회원 장바구니 추가
POST http://localhost:8083/api/cart?bookId=1&quantity=2
X-USER-ID: user123


### 회원 장바구니 추가 (not exist book)
POST http://localhost:8083/api/cart?bookId=10&quantity=2
X-USER-ID: user123