### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET localhost:8280/api/users/apple/orders

### gateway테스트
GET localhost:8180/api/users/apple/orders

### 주문 목록
GET localhost:8280/api/users/A8UmCqn6jwbIIWFAbQ5iPg==/orders

### 주문 상세
GET localhost:8280/api/users/A8UmCqn6jwbIIWFAbQ5iPg==/orders/L9wgkBIV39hcmj-URGZs_w==

### 주문자 확인
GET localhost:8280/api/order/verify?order-id=L9wgkBIV39hcmj-URGZs_w==&user-id=A8UmCqn6jwbIIWFAbQ5iPg==

### 주문자 확인(false)
GET localhost:8280/api/order/verify?order-id=L9wgkBIV39hcmj-URGZs_w==&user-id=A8UmCqn6jwbIIWFAbQ5iPg==2

### 주문 취소
POST localhost:8280/api/order/cancel?order-id=Jm2CEpjNxXwJpozehBvEwQ==